export const ACTION_TYPE = {
  INITIAL_DATA: 'INITIAL_DATA',
  ADD_LIKED: 'ADD_LIKED',
  REMOVE_LIKE_VIDEO: 'REMOVE_LIKE_VIDEO',
  ADD_WATCHLATER: 'ADD_WATCHLATER',
  REMOVE_WATCHLATER: 'REMOVE_WATCHLATER',
  PLAYLIST: 'PLAYLIST',
  VIDEO_PLAYLIST: 'VIDEO_PLAYLIST',
};
